# Generated by Django 3.2.15 on 2022-08-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_orders_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='inputzip',
        ),
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
