# Generated by Django 3.2.15 on 2022-08-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderudate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUdate',
            new_name='OrderUpdate',
        ),
    ]
